import Foundation

final class NotionClient: NotionService, @unchecked Sendable {
    static let notionVersion = "2025-09-03"
    struct Configuration: Sendable { var baseURL: URL; var token: String }
    private let configuration: Configuration; private let session: URLSession
    init(configuration: Configuration, session: URLSession = .shared) { self.configuration = configuration; self.session = session }

    func createPage(_ request: NotionPageRequest) async throws -> NotionPage { try await send(path: "pages", method: "POST", body: ["parent": ["database_id": request.databaseID], "properties": propertiesJSON(request.properties)]) }
    func updatePageProperties(pageID: String, properties: [String: NotionProperty]) async throws { let _: NotionPage = try await send(path: "pages/\(pageID)", method: "PATCH", body: ["properties": propertiesJSON(properties)]) }
    func appendBlocks(pageID: String, blocks: [NotionBlock]) async throws -> [String] { struct Response: Decodable { var results: [ID] }; struct ID: Decodable { var id: String }; let response: Response = try await send(path: "blocks/\(pageID)/children", method: "PATCH", body: ["children": blocks.map(blockJSON)]); return response.results.map(\.id) }
    func listBlocks(pageID: String, cursor: String?) async throws -> NotionBlockPage { struct Response: Decodable { var results: [RemoteBlock]; var hasMore: Bool; var nextCursor: String? }; struct RemoteBlock: Decodable { var id: String; var type: String; var paragraph: Paragraph?; struct Paragraph: Decodable { var richText: [Text]; struct Text: Decodable { var plainText: String } } }; var components = URLComponents(url: configuration.baseURL.appending(path: "blocks/\(pageID)/children"), resolvingAgainstBaseURL: false)!; if let cursor { components.queryItems = [URLQueryItem(name: "start_cursor", value: cursor)] }; let r: Response = try await send(url: components.url!, method: "GET"); return .init(blocks: r.results.map { .init(kind: .paragraph, richText: ($0.paragraph?.richText ?? []).map { .init(content: $0.plainText) }, markerMessageID: nil, remoteID: $0.id) }, hasMore: r.hasMore, nextCursor: r.nextCursor) }
    func createFileUpload(_ request: NotionFileUploadRequest) async throws -> NotionFileUpload { try await send(path: "file_uploads", method: "POST", body: ["filename": request.filename, "content_type": request.contentType]) }
    func sendFile(uploadID: String, fileURL: URL, contentType: String) async throws { let fileData = try Data(contentsOf: fileURL); let boundary = "HappaEcho-\(UUID().uuidString)"; var body = Data(); func append(_ value: String) { body.append(Data(value.utf8)) }; append("--\(boundary)\r\nContent-Disposition: form-data; name=\"file\"; filename=\"\(fileURL.lastPathComponent)\"\r\nContent-Type: \(contentType)\r\n\r\n"); body.append(fileData); append("\r\n--\(boundary)--\r\n"); let _: JSONValue = try await send(path: "file_uploads/\(uploadID)/send", method: "POST", data: body, contentType: "multipart/form-data; boundary=\(boundary)") }
    func completeFileUpload(uploadID: String) async throws -> NotionFileUpload { try await send(path: "file_uploads/\(uploadID)/complete", method: "POST") }

    private func send<T: Decodable>(path: String, method: String, body: [String: Any]? = nil, data: Data? = nil, contentType: String = "application/json") async throws -> T { try await send(url: configuration.baseURL.appending(path: path), method: method, body: body, data: data, contentType: contentType) }
    private func send<T: Decodable>(url: URL, method: String, body: [String: Any]? = nil, data: Data? = nil, contentType: String = "application/json") async throws -> T { var request = URLRequest(url: url); request.httpMethod = method; request.setValue("Bearer \(configuration.token)", forHTTPHeaderField: "Authorization"); request.setValue(Self.notionVersion, forHTTPHeaderField: "Notion-Version"); request.setValue(contentType, forHTTPHeaderField: "Content-Type"); request.httpBody = data ?? (body.map { try! JSONSerialization.data(withJSONObject: $0) }); let responseData: Data; let response: URLResponse; do { (responseData, response) = try await session.data(for: request) } catch let error as URLError { throw NotionError.network(code: error.code.rawValue) } catch { throw NotionError.network(code: nil) }; guard let http = response as? HTTPURLResponse else { throw NotionError.invalidResponse }; guard (200..<300).contains(http.statusCode) else { throw map(status: http.statusCode, retryAfter: http.value(forHTTPHeaderField: "Retry-After")) }; if responseData.isEmpty { return try JSONDecoder().decode(T.self, from: Data("null".utf8)) }; do { let decoder = JSONDecoder(); decoder.keyDecodingStrategy = .convertFromSnakeCase; return try decoder.decode(T.self, from: responseData) } catch { throw NotionError.invalidResponse } }
    private func propertiesJSON(_ properties: [String: NotionProperty]) -> [String: Any] { Dictionary(uniqueKeysWithValues: properties.map { key, value in switch value { case .title(let v): return (key, ["title": [["type": "text", "text": ["content": v]]]]) as (String, Any); case .richText(let v): return (key, ["rich_text": [["type": "text", "text": ["content": v]]]]) as (String, Any); case .date(let v): return (key, ["date": ["start": ISO8601DateFormatter().string(from: v)]]) as (String, Any); case .number(let v): return (key, ["number": v]) as (String, Any); case .select(let v): return (key, ["select": ["name": v]]) as (String, Any) } }) }
    private func blockJSON(_ block: NotionBlock) -> [String: Any] { let key: String; var contents: [String: Any] = ["rich_text": block.richText.map { ["type": "text", "text": ["content": $0.content]] }]; switch block.kind { case .paragraph: key = "paragraph"; case .heading: key = "heading_1"; case .bulletedListItem: key = "bulleted_list_item"; case .quote: key = "quote"; case .code(let language): key = "code"; contents["language"] = language; case .image(let fileUploadID): return ["object": "block", "type": "image", "image": ["type": "file_upload", "file_upload": ["id": fileUploadID], "caption": []]] }; return ["object": "block", "type": key, key: contents] }
    private func map(status: Int, retryAfter: String?) -> NotionError { switch status { case 401: return .unauthorized; case 403: return .forbidden; case 404: return .notFound; case 429: return .rateLimited(retryAfter: retryDelay(retryAfter)); case 500...599: return .server(statusCode: status); default: return .invalidResponse } }
    private func retryDelay(_ header: String?) -> TimeInterval? { guard let header else { return nil }; if let seconds = TimeInterval(header) { return max(0, seconds) }; let formats = ["EEE, dd MMM yyyy HH:mm:ss zzz", "EEEE, dd-MMM-yy HH:mm:ss zzz", "EEE MMM d HH:mm:ss yyyy"]; for format in formats { let formatter = DateFormatter(); formatter.locale = Locale(identifier: "en_US_POSIX"); formatter.timeZone = TimeZone(secondsFromGMT: 0); formatter.dateFormat = format; if let date = formatter.date(from: header) { return max(0, date.timeIntervalSinceNow) } }; return nil }
}
