import Foundation

final class NotionClient: NotionService, @unchecked Sendable {
    static let notionVersion = "2025-09-03"
    struct Configuration: Sendable { var baseURL: URL; var token: String }
    private let configuration: Configuration; private let session: URLSession
    init(configuration: Configuration, session: URLSession = .shared) { self.configuration = configuration; self.session = session }

    func createPage(_ request: NotionPageRequest) async throws -> NotionPage { try await send(path: "pages", method: "POST", body: ["parent": ["database_id": request.databaseID], "properties": propertiesJSON(request.properties)]) }
    func updatePageProperties(pageID: String, properties: [String: NotionProperty]) async throws { let _: NotionPage = try await send(path: "pages/\(pageID)", method: "PATCH", body: ["properties": propertiesJSON(properties)]) }
    func appendBlocks(pageID: String, blocks: [NotionBlock]) async throws -> [String] { struct Response: Decodable { var results: [ID] }; struct ID: Decodable { var id: String }; let response: Response = try await send(path: "blocks/\(pageID)/children", method: "PATCH", body: ["children": blocks.map(blockJSON)]); return response.results.map(\.id) }
    func listBlocks(pageID: String, cursor: String?) async throws -> NotionBlockPage { struct Response: Decodable { var results: [RemoteBlock]; var hasMore: Bool; var nextCursor: String? }; struct RemoteBlock: Decodable { var id: String; var type: String; var paragraph: Paragraph?; struct Paragraph: Decodable { var richText: [Text]; struct Text: Decodable { var plainText: String } } }; var path = "blocks/\(pageID)/children"; if let cursor { path += "?start_cursor=\(cursor.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)" }; let r: Response = try await send(path: path, method: "GET"); return .init(blocks: r.results.map { .init(kind: .paragraph, richText: ($0.paragraph?.richText ?? []).map { .init(content: $0.plainText) }, markerMessageID: nil) }, hasMore: r.hasMore, nextCursor: r.nextCursor) }
    func createFileUpload(_ request: NotionFileUploadRequest) async throws -> NotionFileUpload { try await send(path: "file_uploads", method: "POST", body: ["filename": request.filename, "content_type": request.contentType]) }
    func sendFile(uploadID: String, fileURL: URL) async throws { let data = try Data(contentsOf: fileURL); let _: JSONValue = try await send(path: "file_uploads/\(uploadID)/send", method: "POST", data: data, contentType: "application/octet-stream") }
    func completeFileUpload(uploadID: String) async throws -> NotionFileUpload { try await send(path: "file_uploads/\(uploadID)/complete", method: "POST") }

    private func send<T: Decodable>(path: String, method: String, body: [String: Any]? = nil, data: Data? = nil, contentType: String = "application/json") async throws -> T { var request = URLRequest(url: configuration.baseURL.appending(path: path)); request.httpMethod = method; request.setValue("Bearer \(configuration.token)", forHTTPHeaderField: "Authorization"); request.setValue(Self.notionVersion, forHTTPHeaderField: "Notion-Version"); request.setValue(contentType, forHTTPHeaderField: "Content-Type"); request.httpBody = data ?? (body.map { try! JSONSerialization.data(withJSONObject: $0) }); let (responseData, response) = try await session.data(for: request); guard let http = response as? HTTPURLResponse else { throw NotionError.invalidResponse }; guard (200..<300).contains(http.statusCode) else { throw map(status: http.statusCode, retryAfter: http.value(forHTTPHeaderField: "Retry-After")) }; if responseData.isEmpty { return try JSONDecoder().decode(T.self, from: Data("null".utf8)) }; do { let decoder = JSONDecoder(); decoder.keyDecodingStrategy = .convertFromSnakeCase; return try decoder.decode(T.self, from: responseData) } catch { throw NotionError.invalidResponse } }
    private func propertiesJSON(_ properties: [String: NotionProperty]) -> [String: Any] { Dictionary(uniqueKeysWithValues: properties.map { key, value in switch value { case .title(let v): return (key, ["title": [["type": "text", "text": ["content": v]]]]) as (String, Any); case .richText(let v): return (key, ["rich_text": [["type": "text", "text": ["content": v]]]]) as (String, Any); case .date(let v): return (key, ["date": ["start": ISO8601DateFormatter().string(from: v)]]) as (String, Any); case .number(let v): return (key, ["number": v]) as (String, Any); case .select(let v): return (key, ["select": ["name": v]]) as (String, Any) } }) }
    private func blockJSON(_ block: NotionBlock) -> [String: Any] { let key: String; var contents: [String: Any] = ["rich_text": block.richText.map { ["type": "text", "text": ["content": $0.content]] }]; switch block.kind { case .paragraph: key = "paragraph"; case .heading: key = "heading_1"; case .bulletedListItem: key = "bulleted_list_item"; case .quote: key = "quote"; case .code(let language): key = "code"; contents["language"] = language }; return ["object": "block", "type": key, key: contents] }
    private func map(status: Int, retryAfter: String?) -> NotionError { switch status { case 401: return .unauthorized; case 403: return .forbidden; case 404: return .notFound; case 429: return .rateLimited(retryAfter: TimeInterval(retryAfter ?? "")); case 500...599: return .server(statusCode: status); default: return .invalidResponse } }
}
